### ISSUE TITLE
CountReservations

### ISSUE THREAD

**Issue by danielaltamirano1993** [franclobo/JavaScript-Group-Project#23]
I have reviewed the application, but not code and notice that the reservation fields in the pokemon are detailed in RESERVATIONS[0].

**Comment by franclobo** [comment]
Hi @danielaltamirano1993 
Thank you for your comment 😄.
While developing we noticed that behavior in reservations must be an issue from the API that we used for our application, it is [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to record the different user interactions (likes, comments, and reservations) from Microverse.
